#pragma once
/// @file self_play.h
/// Plays games against itself using MCTSBot + the current V2 model as
/// the policy/value evaluator. Each decision becomes one training
/// tuple: (entity-token snapshot, MCTS visit-count distribution, game
/// outcome from the acting player's view). Tuples are pushed into a
/// ReplayBuffer for the trainer to consume.
///
/// Torch-aware module — includes v2_model.h.

#include "ml/v2_model.h"
#include "ml/v3_model.h"

#include <cstdint>
#include <random>
#include <string>

namespace open_spiel { class Game; }

namespace riftbound::training {

class ReplayBuffer;

struct SelfPlayConfig {
    int num_games      = 100;  // games to play per call
    int mcts_sims      = 50;   // MCTS sims per move
    int max_decisions  = 600;  // cap per game (matches batch_runner)
    double uct_c       = 2.0;  // PUCT exploration constant

    // ── AlphaZero exploration recipe (Phase 6m fix) ──
    // Without these, training data is generated by an MCTS that
    // deterministically follows the model's own (initially-random)
    // prior. Self-play games are nearly identical, the model
    // overfits to one line, and the trained model is worse than
    // random against a real opponent. See logs/baseline_report.md
    // + the 2026-05-18 code review.
    //
    // dirichlet_alpha=0.3, dirichlet_fraction=0.25 match the AlphaZero
    // paper. epsilon=0 disables noise (used in eval / inference).
    double dirichlet_alpha    = 0.3;
    double dirichlet_fraction = 0.25;

    // Temperature for sampling actions from MCTS visit counts at
    // self-play time. temperature=1.0 → sample proportional to visits;
    // temperature=0 → always BestChild (argmax, no exploration).
    // Standard AZ: tau=1 for first 30 moves, tau=0 after.
    double temperature                  = 1.0;
    int    temperature_drop_at_decision = 30;

    // Phase 6q — MCTS-bootstrap mode. When false, runSelfPlay uses
    // OpenSpiel's RandomRolloutEvaluator (pure MCTS — no model in the
    // loop) and the `model` argument is ignored for evaluation. Use
    // for the warm-start phase before the model can produce a useful
    // prior. Tuples (entity_tokens, π, z) are pushed to the buffer
    // exactly as in model-driven self-play, so the trainer learns to
    // imitate MCTS from those targets. After bootstrap, flip this to
    // true and the bot consults the V2 model for prior + value.
    bool use_model = true;

    // Phase 6v — model architecture selector. Drives both the
    // self-play tuple capture (V2 stores entity_tokens, V3 stores
    // flat_state) and the inference path used when use_model=true.
    // "v2" (default) preserves legacy behavior.
    std::string model_kind = "v2";

    bool verbose       = false; // log per-game progress to stderr
};

struct SelfPlayStats {
    int games_played    = 0;
    int p1_wins         = 0;
    int p2_wins         = 0;
    int draws           = 0;
    int64_t tuples_added = 0;
    int64_t total_decisions = 0;
    // Phase 6o follow-up — break down draws by exit reason.
    // `exit_terminal_*` counts games where state.IsTerminal() became
    // true (natural end). `exit_cap` counts games that hit
    // max_decisions. `exit_stuck` counts games where legal_actions
    // returned empty mid-game (likely engine bug). For "drawn" games
    // (returns[0]==returns[1]==0), the exit reason tells you which
    // path produced the draw.
    int exit_terminal = 0;
    int exit_cap      = 0;
    int exit_stuck    = 0;
    // For the most-recent game played, the single exit reason (so
    // config_driver can tag the per-game log line). 0=terminal, 1=cap,
    // 2=stuck. Matches ExitReason enum order.
    int last_exit_reason = 0;
};

/// Run `cfg.num_games` self-play games using the supplied V2 model.
/// Pushes (entity_tokens, π, z) tuples for every decision point into
/// `buffer`. The MCTSBot for each game uses an Evaluator that shares
/// the model instance — after a trainer optimizer step, the next
/// self-play game sees the updated parameters without any disk
/// round-trip.
SelfPlayStats runSelfPlay(const ::open_spiel::Game& game,
                           ::riftbound::ml::V2Model model,
                           ReplayBuffer& buffer,
                           const SelfPlayConfig& cfg,
                           std::mt19937& rng,
                           int iter      = -1,
                           int game_idx  = -1);

/// Phase 6v — same self-play loop, but driving a V3 (flat-feature MLP)
/// model. Capture flat_state into ReplaySample (instead of entity_tokens)
/// and use the V3 evaluator when cfg.use_model is true.
SelfPlayStats runSelfPlayV3(const ::open_spiel::Game& game,
                             ::riftbound::ml::V3Model model,
                             ReplayBuffer& buffer,
                             const SelfPlayConfig& cfg,
                             std::mt19937& rng,
                             int iter      = -1,
                             int game_idx  = -1);

} // namespace riftbound::training
