// Auto-generated aggregator — registers all per-card files.
#include "cards/card_registry.h"

namespace riftbound {

void register_card_1(CardRegistry&);
void register_card_2(CardRegistry&);
void register_card_3(CardRegistry&);
void register_card_4(CardRegistry&);
void register_card_5(CardRegistry&);
void register_card_6(CardRegistry&);
void register_card_7(CardRegistry&);
void register_card_8(CardRegistry&);
void register_card_9(CardRegistry&);
void register_card_10(CardRegistry&);
void register_card_11(CardRegistry&);
void register_card_12(CardRegistry&);
void register_card_13(CardRegistry&);
void register_card_14(CardRegistry&);
void register_card_15(CardRegistry&);
void register_card_16(CardRegistry&);
void register_card_17(CardRegistry&);
void register_card_18(CardRegistry&);
void register_card_19(CardRegistry&);
void register_card_20(CardRegistry&);
void register_card_21(CardRegistry&);
void register_card_22(CardRegistry&);
void register_card_23(CardRegistry&);
void register_card_24(CardRegistry&);
void register_card_25(CardRegistry&);
void register_card_26(CardRegistry&);
void register_card_27(CardRegistry&);
void register_card_28(CardRegistry&);
void register_card_29(CardRegistry&);
void register_card_30(CardRegistry&);
void register_card_31(CardRegistry&);
void register_card_32(CardRegistry&);
void register_card_33(CardRegistry&);
void register_card_34(CardRegistry&);
void register_card_35(CardRegistry&);
void register_card_36(CardRegistry&);
void register_card_37(CardRegistry&);
void register_card_38(CardRegistry&);
void register_card_39(CardRegistry&);
void register_card_40(CardRegistry&);
void register_card_41(CardRegistry&);
void register_card_42(CardRegistry&);
void register_card_43(CardRegistry&);
void register_card_44(CardRegistry&);
void register_card_45(CardRegistry&);
void register_card_46(CardRegistry&);
void register_card_47(CardRegistry&);
void register_card_48(CardRegistry&);
void register_card_49(CardRegistry&);
void register_card_50(CardRegistry&);
void register_card_51(CardRegistry&);
void register_card_52(CardRegistry&);
void register_card_53(CardRegistry&);
void register_card_54(CardRegistry&);
void register_card_55(CardRegistry&);
void register_card_56(CardRegistry&);
void register_card_57(CardRegistry&);
void register_card_58(CardRegistry&);
void register_card_59(CardRegistry&);
void register_card_60(CardRegistry&);
void register_card_61(CardRegistry&);
void register_card_62(CardRegistry&);
void register_card_63(CardRegistry&);
void register_card_64(CardRegistry&);
void register_card_65(CardRegistry&);
void register_card_66(CardRegistry&);
void register_card_67(CardRegistry&);
void register_card_68(CardRegistry&);
void register_card_69(CardRegistry&);
void register_card_70(CardRegistry&);
void register_card_71(CardRegistry&);
void register_card_72(CardRegistry&);
void register_card_73(CardRegistry&);
void register_card_74(CardRegistry&);
void register_card_75(CardRegistry&);
void register_card_76(CardRegistry&);
void register_card_77(CardRegistry&);
void register_card_78(CardRegistry&);
void register_card_79(CardRegistry&);
void register_card_80(CardRegistry&);
void register_card_81(CardRegistry&);
void register_card_82(CardRegistry&);
void register_card_83(CardRegistry&);
void register_card_84(CardRegistry&);
void register_card_85(CardRegistry&);
void register_card_86(CardRegistry&);
void register_card_87(CardRegistry&);
void register_card_88(CardRegistry&);
void register_card_89(CardRegistry&);
void register_card_90(CardRegistry&);
void register_card_91(CardRegistry&);
void register_card_92(CardRegistry&);
void register_card_93(CardRegistry&);
void register_card_94(CardRegistry&);
void register_card_95(CardRegistry&);
void register_card_96(CardRegistry&);
void register_card_97(CardRegistry&);
void register_card_98(CardRegistry&);
void register_card_99(CardRegistry&);
void register_card_100(CardRegistry&);
void register_card_101(CardRegistry&);
void register_card_102(CardRegistry&);
void register_card_103(CardRegistry&);
void register_card_104(CardRegistry&);
void register_card_105(CardRegistry&);
void register_card_106(CardRegistry&);
void register_card_107(CardRegistry&);
void register_card_108(CardRegistry&);
void register_card_109(CardRegistry&);
void register_card_110(CardRegistry&);
void register_card_111(CardRegistry&);
void register_card_112(CardRegistry&);
void register_card_113(CardRegistry&);
void register_card_114(CardRegistry&);
void register_card_115(CardRegistry&);
void register_card_116(CardRegistry&);
void register_card_117(CardRegistry&);
void register_card_118(CardRegistry&);
void register_card_119(CardRegistry&);
void register_card_120(CardRegistry&);
void register_card_121(CardRegistry&);
void register_card_122(CardRegistry&);
void register_card_123(CardRegistry&);
void register_card_124(CardRegistry&);
void register_card_125(CardRegistry&);
void register_card_126(CardRegistry&);
void register_card_127(CardRegistry&);
void register_card_128(CardRegistry&);
void register_card_129(CardRegistry&);
void register_card_130(CardRegistry&);
void register_card_131(CardRegistry&);
void register_card_132(CardRegistry&);
void register_card_133(CardRegistry&);
void register_card_134(CardRegistry&);
void register_card_135(CardRegistry&);
void register_card_136(CardRegistry&);
void register_card_137(CardRegistry&);
void register_card_138(CardRegistry&);
void register_card_139(CardRegistry&);
void register_card_140(CardRegistry&);
void register_card_141(CardRegistry&);
void register_card_142(CardRegistry&);
void register_card_143(CardRegistry&);
void register_card_144(CardRegistry&);
void register_card_145(CardRegistry&);
void register_card_146(CardRegistry&);
void register_card_147(CardRegistry&);
void register_card_148(CardRegistry&);
void register_card_149(CardRegistry&);
void register_card_150(CardRegistry&);
void register_card_151(CardRegistry&);
void register_card_152(CardRegistry&);
void register_card_153(CardRegistry&);
void register_card_154(CardRegistry&);
void register_card_155(CardRegistry&);
void register_card_156(CardRegistry&);
void register_card_157(CardRegistry&);
void register_card_158(CardRegistry&);
void register_card_159(CardRegistry&);
void register_card_160(CardRegistry&);
void register_card_161(CardRegistry&);
void register_card_162(CardRegistry&);
void register_card_163(CardRegistry&);
void register_card_164(CardRegistry&);
void register_card_165(CardRegistry&);
void register_card_166(CardRegistry&);
void register_card_167(CardRegistry&);
void register_card_168(CardRegistry&);
void register_card_169(CardRegistry&);
void register_card_170(CardRegistry&);
void register_card_171(CardRegistry&);
void register_card_172(CardRegistry&);
void register_card_173(CardRegistry&);
void register_card_174(CardRegistry&);
void register_card_175(CardRegistry&);
void register_card_176(CardRegistry&);
void register_card_177(CardRegistry&);
void register_card_178(CardRegistry&);
void register_card_179(CardRegistry&);
void register_card_180(CardRegistry&);
void register_card_181(CardRegistry&);
void register_card_182(CardRegistry&);
void register_card_183(CardRegistry&);
void register_card_184(CardRegistry&);
void register_card_185(CardRegistry&);
void register_card_186(CardRegistry&);
void register_card_187(CardRegistry&);
void register_card_188(CardRegistry&);
void register_card_189(CardRegistry&);
void register_card_190(CardRegistry&);
void register_card_191(CardRegistry&);
void register_card_192(CardRegistry&);
void register_card_193(CardRegistry&);
void register_card_194(CardRegistry&);
void register_card_195(CardRegistry&);
void register_card_196(CardRegistry&);
void register_card_197(CardRegistry&);
void register_card_198(CardRegistry&);
void register_card_199(CardRegistry&);
void register_card_200(CardRegistry&);
void register_card_201(CardRegistry&);
void register_card_202(CardRegistry&);
void register_card_203(CardRegistry&);
void register_card_204(CardRegistry&);
void register_card_205(CardRegistry&);
void register_card_206(CardRegistry&);
void register_card_207(CardRegistry&);
void register_card_208(CardRegistry&);
void register_card_209(CardRegistry&);
void register_card_210(CardRegistry&);
void register_card_211(CardRegistry&);
void register_card_212(CardRegistry&);
void register_card_213(CardRegistry&);
void register_card_214(CardRegistry&);
void register_card_215(CardRegistry&);
void register_card_216(CardRegistry&);
void register_card_217(CardRegistry&);
void register_card_218(CardRegistry&);
void register_card_219(CardRegistry&);
void register_card_220(CardRegistry&);
void register_card_221(CardRegistry&);
void register_card_222(CardRegistry&);
void register_card_223(CardRegistry&);
void register_card_224(CardRegistry&);
void register_card_225(CardRegistry&);
void register_card_226(CardRegistry&);
void register_card_227(CardRegistry&);
void register_card_228(CardRegistry&);
void register_card_229(CardRegistry&);
void register_card_230(CardRegistry&);
void register_card_231(CardRegistry&);
void register_card_232(CardRegistry&);
void register_card_233(CardRegistry&);
void register_card_234(CardRegistry&);
void register_card_235(CardRegistry&);
void register_card_236(CardRegistry&);
void register_card_237(CardRegistry&);
void register_card_238(CardRegistry&);
void register_card_239(CardRegistry&);
void register_card_240(CardRegistry&);
void register_card_241(CardRegistry&);
void register_card_242(CardRegistry&);
void register_card_243(CardRegistry&);
void register_card_244(CardRegistry&);
void register_card_245(CardRegistry&);
void register_card_246(CardRegistry&);
void register_card_247(CardRegistry&);
void register_card_248(CardRegistry&);
void register_card_249(CardRegistry&);
void register_card_250(CardRegistry&);
void register_card_251(CardRegistry&);
void register_card_252(CardRegistry&);
void register_card_253(CardRegistry&);
void register_card_254(CardRegistry&);
void register_card_255(CardRegistry&);
void register_card_256(CardRegistry&);
void register_card_257(CardRegistry&);
void register_card_258(CardRegistry&);
void register_card_259(CardRegistry&);
void register_card_260(CardRegistry&);
void register_card_261(CardRegistry&);
void register_card_262(CardRegistry&);
void register_card_263(CardRegistry&);
void register_card_264(CardRegistry&);
void register_card_265(CardRegistry&);
void register_card_266(CardRegistry&);
void register_card_267(CardRegistry&);
void register_card_268(CardRegistry&);
void register_card_269(CardRegistry&);
void register_card_270(CardRegistry&);
void register_card_271(CardRegistry&);
void register_card_272(CardRegistry&);
void register_card_273(CardRegistry&);
void register_card_274(CardRegistry&);
void register_card_275(CardRegistry&);
void register_card_276(CardRegistry&);
void register_card_277(CardRegistry&);
void register_card_278(CardRegistry&);
void register_card_279(CardRegistry&);
void register_card_280(CardRegistry&);
void register_card_281(CardRegistry&);
void register_card_282(CardRegistry&);
void register_card_283(CardRegistry&);
void register_card_284(CardRegistry&);
void register_card_285(CardRegistry&);
void register_card_286(CardRegistry&);
void register_card_287(CardRegistry&);
void register_card_288(CardRegistry&);
void register_card_289(CardRegistry&);
void register_card_290(CardRegistry&);
void register_card_291(CardRegistry&);
void register_card_292(CardRegistry&);
void register_card_293(CardRegistry&);
void register_card_294(CardRegistry&);
void register_card_295(CardRegistry&);
void register_card_296(CardRegistry&);
void register_card_297(CardRegistry&);
void register_card_298(CardRegistry&);
void register_card_299(CardRegistry&);
void register_card_300(CardRegistry&);
void register_card_301(CardRegistry&);
void register_card_302(CardRegistry&);
void register_card_303(CardRegistry&);
void register_card_304(CardRegistry&);
void register_card_305(CardRegistry&);
void register_card_306(CardRegistry&);
void register_card_307(CardRegistry&);
void register_card_308(CardRegistry&);
void register_card_309(CardRegistry&);
void register_card_310(CardRegistry&);
void register_card_311(CardRegistry&);
void register_card_312(CardRegistry&);
void register_card_313(CardRegistry&);
void register_card_314(CardRegistry&);
void register_card_315(CardRegistry&);
void register_card_316(CardRegistry&);
void register_card_317(CardRegistry&);
void register_card_318(CardRegistry&);
void register_card_319(CardRegistry&);
void register_card_320(CardRegistry&);
void register_card_321(CardRegistry&);
void register_card_322(CardRegistry&);
void register_card_323(CardRegistry&);
void register_card_324(CardRegistry&);
void register_card_325(CardRegistry&);
void register_card_326(CardRegistry&);
void register_card_327(CardRegistry&);
void register_card_328(CardRegistry&);
void register_card_329(CardRegistry&);
void register_card_330(CardRegistry&);
void register_card_331(CardRegistry&);
void register_card_332(CardRegistry&);
void register_card_333(CardRegistry&);
void register_card_334(CardRegistry&);
void register_card_335(CardRegistry&);
void register_card_336(CardRegistry&);
void register_card_337(CardRegistry&);
void register_card_338(CardRegistry&);
void register_card_339(CardRegistry&);
void register_card_340(CardRegistry&);
void register_card_341(CardRegistry&);
void register_card_342(CardRegistry&);
void register_card_343(CardRegistry&);
void register_card_344(CardRegistry&);
void register_card_345(CardRegistry&);
void register_card_346(CardRegistry&);
void register_card_347(CardRegistry&);
void register_card_348(CardRegistry&);
void register_card_349(CardRegistry&);
void register_card_350(CardRegistry&);
void register_card_351(CardRegistry&);
void register_card_352(CardRegistry&);
void register_card_353(CardRegistry&);
void register_card_354(CardRegistry&);
void register_card_355(CardRegistry&);
void register_card_356(CardRegistry&);
void register_card_357(CardRegistry&);
void register_card_358(CardRegistry&);
void register_card_359(CardRegistry&);
void register_card_360(CardRegistry&);
void register_card_361(CardRegistry&);
void register_card_362(CardRegistry&);
void register_card_363(CardRegistry&);
void register_card_364(CardRegistry&);
void register_card_365(CardRegistry&);
void register_card_366(CardRegistry&);
void register_card_367(CardRegistry&);
void register_card_368(CardRegistry&);
void register_card_369(CardRegistry&);
void register_card_370(CardRegistry&);
void register_card_371(CardRegistry&);
void register_card_372(CardRegistry&);
void register_card_373(CardRegistry&);
void register_card_374(CardRegistry&);
void register_card_375(CardRegistry&);
void register_card_376(CardRegistry&);
void register_card_377(CardRegistry&);
void register_card_378(CardRegistry&);
void register_card_379(CardRegistry&);
void register_card_380(CardRegistry&);
void register_card_381(CardRegistry&);
void register_card_382(CardRegistry&);
void register_card_383(CardRegistry&);
void register_card_384(CardRegistry&);
void register_card_385(CardRegistry&);
void register_card_386(CardRegistry&);
void register_card_387(CardRegistry&);
void register_card_388(CardRegistry&);
void register_card_389(CardRegistry&);
void register_card_390(CardRegistry&);
void register_card_391(CardRegistry&);
void register_card_392(CardRegistry&);
void register_card_393(CardRegistry&);
void register_card_394(CardRegistry&);
void register_card_395(CardRegistry&);
void register_card_396(CardRegistry&);
void register_card_397(CardRegistry&);
void register_card_398(CardRegistry&);
void register_card_399(CardRegistry&);
void register_card_400(CardRegistry&);
void register_card_401(CardRegistry&);
void register_card_402(CardRegistry&);
void register_card_403(CardRegistry&);
void register_card_404(CardRegistry&);
void register_card_405(CardRegistry&);
void register_card_406(CardRegistry&);
void register_card_407(CardRegistry&);
void register_card_408(CardRegistry&);
void register_card_409(CardRegistry&);
void register_card_410(CardRegistry&);
void register_card_411(CardRegistry&);
void register_card_412(CardRegistry&);
void register_card_413(CardRegistry&);
void register_card_414(CardRegistry&);
void register_card_415(CardRegistry&);
void register_card_416(CardRegistry&);
void register_card_417(CardRegistry&);
void register_card_418(CardRegistry&);
void register_card_419(CardRegistry&);
void register_card_420(CardRegistry&);
void register_card_421(CardRegistry&);
void register_card_422(CardRegistry&);
void register_card_423(CardRegistry&);
void register_card_424(CardRegistry&);
void register_card_425(CardRegistry&);
void register_card_426(CardRegistry&);
void register_card_427(CardRegistry&);
void register_card_428(CardRegistry&);
void register_card_429(CardRegistry&);
void register_card_430(CardRegistry&);
void register_card_431(CardRegistry&);
void register_card_432(CardRegistry&);
void register_card_433(CardRegistry&);
void register_card_434(CardRegistry&);
void register_card_435(CardRegistry&);
void register_card_436(CardRegistry&);
void register_card_437(CardRegistry&);
void register_card_438(CardRegistry&);
void register_card_439(CardRegistry&);
void register_card_440(CardRegistry&);
void register_card_441(CardRegistry&);
void register_card_442(CardRegistry&);
void register_card_443(CardRegistry&);
void register_card_444(CardRegistry&);
void register_card_445(CardRegistry&);
void register_card_446(CardRegistry&);
void register_card_447(CardRegistry&);
void register_card_448(CardRegistry&);
void register_card_449(CardRegistry&);
void register_card_450(CardRegistry&);
void register_card_451(CardRegistry&);
void register_card_452(CardRegistry&);
void register_card_453(CardRegistry&);
void register_card_454(CardRegistry&);
void register_card_455(CardRegistry&);
void register_card_456(CardRegistry&);
void register_card_457(CardRegistry&);
void register_card_458(CardRegistry&);
void register_card_459(CardRegistry&);
void register_card_460(CardRegistry&);
void register_card_461(CardRegistry&);
void register_card_462(CardRegistry&);
void register_card_463(CardRegistry&);
void register_card_464(CardRegistry&);
void register_card_465(CardRegistry&);
void register_card_466(CardRegistry&);
void register_card_467(CardRegistry&);
void register_card_468(CardRegistry&);
void register_card_469(CardRegistry&);
void register_card_470(CardRegistry&);
void register_card_471(CardRegistry&);
void register_card_472(CardRegistry&);
void register_card_473(CardRegistry&);
void register_card_474(CardRegistry&);
void register_card_475(CardRegistry&);
void register_card_476(CardRegistry&);
void register_card_477(CardRegistry&);
void register_card_478(CardRegistry&);
void register_card_479(CardRegistry&);
void register_card_480(CardRegistry&);
void register_card_481(CardRegistry&);
void register_card_482(CardRegistry&);
void register_card_483(CardRegistry&);
void register_card_484(CardRegistry&);
void register_card_485(CardRegistry&);
void register_card_486(CardRegistry&);
void register_card_487(CardRegistry&);
void register_card_488(CardRegistry&);
void register_card_489(CardRegistry&);
void register_card_490(CardRegistry&);
void register_card_491(CardRegistry&);
void register_card_492(CardRegistry&);
void register_card_493(CardRegistry&);
void register_card_494(CardRegistry&);
void register_card_495(CardRegistry&);
void register_card_496(CardRegistry&);
void register_card_497(CardRegistry&);
void register_card_498(CardRegistry&);
void register_card_499(CardRegistry&);
void register_card_500(CardRegistry&);
void register_card_501(CardRegistry&);
void register_card_502(CardRegistry&);
void register_card_503(CardRegistry&);
void register_card_504(CardRegistry&);
void register_card_505(CardRegistry&);
void register_card_506(CardRegistry&);
void register_card_507(CardRegistry&);
void register_card_508(CardRegistry&);
void register_card_509(CardRegistry&);
void register_card_510(CardRegistry&);
void register_card_511(CardRegistry&);
void register_card_512(CardRegistry&);
void register_card_513(CardRegistry&);
void register_card_514(CardRegistry&);
void register_card_515(CardRegistry&);
void register_card_516(CardRegistry&);
void register_card_517(CardRegistry&);
void register_card_518(CardRegistry&);
void register_card_519(CardRegistry&);
void register_card_520(CardRegistry&);
void register_card_521(CardRegistry&);
void register_card_522(CardRegistry&);
void register_card_523(CardRegistry&);
void register_card_524(CardRegistry&);
void register_card_525(CardRegistry&);
void register_card_526(CardRegistry&);
void register_card_527(CardRegistry&);
void register_card_528(CardRegistry&);
void register_card_529(CardRegistry&);
void register_card_530(CardRegistry&);
void register_card_531(CardRegistry&);
void register_card_532(CardRegistry&);
void register_card_533(CardRegistry&);
void register_card_534(CardRegistry&);
void register_card_535(CardRegistry&);
void register_card_536(CardRegistry&);
void register_card_537(CardRegistry&);
void register_card_538(CardRegistry&);
void register_card_539(CardRegistry&);
void register_card_540(CardRegistry&);
void register_card_541(CardRegistry&);
void register_card_542(CardRegistry&);
void register_card_543(CardRegistry&);
void register_card_544(CardRegistry&);
void register_card_545(CardRegistry&);
void register_card_546(CardRegistry&);
void register_card_547(CardRegistry&);
void register_card_548(CardRegistry&);
void register_card_549(CardRegistry&);
void register_card_550(CardRegistry&);
void register_card_551(CardRegistry&);
void register_card_552(CardRegistry&);
void register_card_553(CardRegistry&);
void register_card_554(CardRegistry&);
void register_card_555(CardRegistry&);
void register_card_556(CardRegistry&);
void register_card_557(CardRegistry&);
void register_card_558(CardRegistry&);
void register_card_559(CardRegistry&);
void register_card_560(CardRegistry&);
void register_card_561(CardRegistry&);
void register_card_562(CardRegistry&);
void register_card_563(CardRegistry&);
void register_card_564(CardRegistry&);
void register_card_565(CardRegistry&);
void register_card_566(CardRegistry&);
void register_card_567(CardRegistry&);
void register_card_568(CardRegistry&);
void register_card_569(CardRegistry&);
void register_card_570(CardRegistry&);
void register_card_571(CardRegistry&);
void register_card_572(CardRegistry&);
void register_card_573(CardRegistry&);
void register_card_574(CardRegistry&);
void register_card_575(CardRegistry&);
void register_card_576(CardRegistry&);
void register_card_577(CardRegistry&);
void register_card_578(CardRegistry&);
void register_card_579(CardRegistry&);
void register_card_580(CardRegistry&);
void register_card_581(CardRegistry&);
void register_card_582(CardRegistry&);
void register_card_583(CardRegistry&);
void register_card_584(CardRegistry&);
void register_card_585(CardRegistry&);
void register_card_586(CardRegistry&);
void register_card_587(CardRegistry&);
void register_card_588(CardRegistry&);
void register_card_589(CardRegistry&);
void register_card_590(CardRegistry&);
void register_card_591(CardRegistry&);
void register_card_592(CardRegistry&);
void register_card_593(CardRegistry&);
void register_card_594(CardRegistry&);
void register_card_595(CardRegistry&);
void register_card_596(CardRegistry&);
void register_card_597(CardRegistry&);
void register_card_598(CardRegistry&);
void register_card_599(CardRegistry&);
void register_card_600(CardRegistry&);
void register_card_601(CardRegistry&);
void register_card_602(CardRegistry&);
void register_card_603(CardRegistry&);
void register_card_604(CardRegistry&);
void register_card_605(CardRegistry&);
void register_card_606(CardRegistry&);
void register_card_607(CardRegistry&);
void register_card_608(CardRegistry&);
void register_card_609(CardRegistry&);
void register_card_610(CardRegistry&);
void register_card_611(CardRegistry&);
void register_card_612(CardRegistry&);
void register_card_613(CardRegistry&);
void register_card_614(CardRegistry&);
void register_card_615(CardRegistry&);
void register_card_616(CardRegistry&);
void register_card_617(CardRegistry&);
void register_card_618(CardRegistry&);
void register_card_619(CardRegistry&);
void register_card_620(CardRegistry&);
void register_card_621(CardRegistry&);
void register_card_622(CardRegistry&);
void register_card_623(CardRegistry&);
void register_card_624(CardRegistry&);
void register_card_625(CardRegistry&);
void register_card_626(CardRegistry&);
void register_card_627(CardRegistry&);
void register_card_628(CardRegistry&);
void register_card_629(CardRegistry&);
void register_card_630(CardRegistry&);
void register_card_631(CardRegistry&);
void register_card_632(CardRegistry&);
void register_card_633(CardRegistry&);
void register_card_634(CardRegistry&);
void register_card_635(CardRegistry&);
void register_card_636(CardRegistry&);
void register_card_637(CardRegistry&);
void register_card_638(CardRegistry&);
void register_card_639(CardRegistry&);
void register_card_640(CardRegistry&);
void register_card_641(CardRegistry&);
void register_card_642(CardRegistry&);
void register_card_643(CardRegistry&);
void register_card_644(CardRegistry&);
void register_card_645(CardRegistry&);
void register_card_646(CardRegistry&);
void register_card_647(CardRegistry&);
void register_card_648(CardRegistry&);
void register_card_649(CardRegistry&);
void register_card_650(CardRegistry&);
void register_card_651(CardRegistry&);
void register_card_652(CardRegistry&);
void register_card_653(CardRegistry&);
void register_card_654(CardRegistry&);
void register_card_655(CardRegistry&);
void register_card_656(CardRegistry&);
void register_card_657(CardRegistry&);
void register_card_658(CardRegistry&);
void register_card_659(CardRegistry&);
void register_card_660(CardRegistry&);
void register_card_661(CardRegistry&);
void register_card_662(CardRegistry&);
void register_card_663(CardRegistry&);
void register_card_664(CardRegistry&);
void register_card_665(CardRegistry&);
void register_card_666(CardRegistry&);
void register_card_667(CardRegistry&);
void register_card_668(CardRegistry&);
void register_card_669(CardRegistry&);
void register_card_670(CardRegistry&);
void register_card_671(CardRegistry&);
void register_card_672(CardRegistry&);
void register_card_673(CardRegistry&);
void register_card_674(CardRegistry&);
void register_card_675(CardRegistry&);
void register_card_676(CardRegistry&);
void register_card_677(CardRegistry&);
void register_card_678(CardRegistry&);
void register_card_679(CardRegistry&);
void register_card_680(CardRegistry&);
void register_card_681(CardRegistry&);
void register_card_682(CardRegistry&);
void register_card_683(CardRegistry&);
void register_card_684(CardRegistry&);
void register_card_685(CardRegistry&);
void register_card_686(CardRegistry&);
void register_card_687(CardRegistry&);
void register_card_688(CardRegistry&);
void register_card_689(CardRegistry&);
void register_card_690(CardRegistry&);
void register_card_691(CardRegistry&);
void register_card_692(CardRegistry&);
void register_card_693(CardRegistry&);
void register_card_694(CardRegistry&);
void register_card_695(CardRegistry&);
void register_card_696(CardRegistry&);
void register_card_697(CardRegistry&);
void register_card_698(CardRegistry&);
void register_card_699(CardRegistry&);
void register_card_700(CardRegistry&);
void register_card_701(CardRegistry&);
void register_card_702(CardRegistry&);
void register_card_703(CardRegistry&);
void register_card_704(CardRegistry&);
void register_card_705(CardRegistry&);
void register_card_706(CardRegistry&);
void register_card_707(CardRegistry&);
void register_card_708(CardRegistry&);
void register_card_709(CardRegistry&);
void register_card_710(CardRegistry&);
void register_card_711(CardRegistry&);
void register_card_712(CardRegistry&);
void register_card_713(CardRegistry&);
void register_card_714(CardRegistry&);
void register_card_715(CardRegistry&);
void register_card_716(CardRegistry&);
void register_card_717(CardRegistry&);
void register_card_718(CardRegistry&);
void register_card_719(CardRegistry&);
void register_card_720(CardRegistry&);
void register_card_721(CardRegistry&);
void register_card_722(CardRegistry&);
void register_card_723(CardRegistry&);
void register_card_724(CardRegistry&);
void register_card_725(CardRegistry&);
void register_card_726(CardRegistry&);
void register_card_727(CardRegistry&);
void register_card_728(CardRegistry&);
void register_card_729(CardRegistry&);
void register_card_730(CardRegistry&);
void register_card_731(CardRegistry&);
void register_card_732(CardRegistry&);
void register_card_733(CardRegistry&);
void register_card_734(CardRegistry&);
void register_card_735(CardRegistry&);
void register_card_736(CardRegistry&);
void register_card_737(CardRegistry&);
void register_card_738(CardRegistry&);
void register_card_739(CardRegistry&);
void register_card_740(CardRegistry&);
void register_card_741(CardRegistry&);
void register_card_742(CardRegistry&);
void register_card_743(CardRegistry&);
void register_card_744(CardRegistry&);
void register_card_745(CardRegistry&);
void register_card_746(CardRegistry&);
void register_card_747(CardRegistry&);
void register_card_748(CardRegistry&);
void register_card_749(CardRegistry&);
void register_card_750(CardRegistry&);
void register_card_751(CardRegistry&);
void register_card_752(CardRegistry&);
void register_card_753(CardRegistry&);
void register_card_754(CardRegistry&);
void register_card_755(CardRegistry&);
void register_card_756(CardRegistry&);
void register_card_757(CardRegistry&);
void register_card_758(CardRegistry&);
void register_card_759(CardRegistry&);
void register_card_760(CardRegistry&);
void register_card_761(CardRegistry&);
void register_card_762(CardRegistry&);
void register_card_763(CardRegistry&);
void register_card_764(CardRegistry&);
void register_card_765(CardRegistry&);
void register_card_766(CardRegistry&);
void register_card_767(CardRegistry&);
void register_card_768(CardRegistry&);
void register_card_769(CardRegistry&);
void register_card_770(CardRegistry&);
void register_card_771(CardRegistry&);
void register_card_772(CardRegistry&);
void register_card_773(CardRegistry&);
void register_card_774(CardRegistry&);
void register_card_775(CardRegistry&);
void register_card_776(CardRegistry&);
void register_card_777(CardRegistry&);
void register_card_778(CardRegistry&);
void register_card_779(CardRegistry&);
void register_card_780(CardRegistry&);
void register_card_781(CardRegistry&);
void register_card_782(CardRegistry&);
void register_card_783(CardRegistry&);
void register_card_784(CardRegistry&);
void register_card_785(CardRegistry&);
void register_card_786(CardRegistry&);
void register_card_787(CardRegistry&);

void registerAllCards(CardRegistry& registry) {
    register_card_1(registry);
    register_card_2(registry);
    register_card_3(registry);
    register_card_4(registry);
    register_card_5(registry);
    register_card_6(registry);
    register_card_7(registry);
    register_card_8(registry);
    register_card_9(registry);
    register_card_10(registry);
    register_card_11(registry);
    register_card_12(registry);
    register_card_13(registry);
    register_card_14(registry);
    register_card_15(registry);
    register_card_16(registry);
    register_card_17(registry);
    register_card_18(registry);
    register_card_19(registry);
    register_card_20(registry);
    register_card_21(registry);
    register_card_22(registry);
    register_card_23(registry);
    register_card_24(registry);
    register_card_25(registry);
    register_card_26(registry);
    register_card_27(registry);
    register_card_28(registry);
    register_card_29(registry);
    register_card_30(registry);
    register_card_31(registry);
    register_card_32(registry);
    register_card_33(registry);
    register_card_34(registry);
    register_card_35(registry);
    register_card_36(registry);
    register_card_37(registry);
    register_card_38(registry);
    register_card_39(registry);
    register_card_40(registry);
    register_card_41(registry);
    register_card_42(registry);
    register_card_43(registry);
    register_card_44(registry);
    register_card_45(registry);
    register_card_46(registry);
    register_card_47(registry);
    register_card_48(registry);
    register_card_49(registry);
    register_card_50(registry);
    register_card_51(registry);
    register_card_52(registry);
    register_card_53(registry);
    register_card_54(registry);
    register_card_55(registry);
    register_card_56(registry);
    register_card_57(registry);
    register_card_58(registry);
    register_card_59(registry);
    register_card_60(registry);
    register_card_61(registry);
    register_card_62(registry);
    register_card_63(registry);
    register_card_64(registry);
    register_card_65(registry);
    register_card_66(registry);
    register_card_67(registry);
    register_card_68(registry);
    register_card_69(registry);
    register_card_70(registry);
    register_card_71(registry);
    register_card_72(registry);
    register_card_73(registry);
    register_card_74(registry);
    register_card_75(registry);
    register_card_76(registry);
    register_card_77(registry);
    register_card_78(registry);
    register_card_79(registry);
    register_card_80(registry);
    register_card_81(registry);
    register_card_82(registry);
    register_card_83(registry);
    register_card_84(registry);
    register_card_85(registry);
    register_card_86(registry);
    register_card_87(registry);
    register_card_88(registry);
    register_card_89(registry);
    register_card_90(registry);
    register_card_91(registry);
    register_card_92(registry);
    register_card_93(registry);
    register_card_94(registry);
    register_card_95(registry);
    register_card_96(registry);
    register_card_97(registry);
    register_card_98(registry);
    register_card_99(registry);
    register_card_100(registry);
    register_card_101(registry);
    register_card_102(registry);
    register_card_103(registry);
    register_card_104(registry);
    register_card_105(registry);
    register_card_106(registry);
    register_card_107(registry);
    register_card_108(registry);
    register_card_109(registry);
    register_card_110(registry);
    register_card_111(registry);
    register_card_112(registry);
    register_card_113(registry);
    register_card_114(registry);
    register_card_115(registry);
    register_card_116(registry);
    register_card_117(registry);
    register_card_118(registry);
    register_card_119(registry);
    register_card_120(registry);
    register_card_121(registry);
    register_card_122(registry);
    register_card_123(registry);
    register_card_124(registry);
    register_card_125(registry);
    register_card_126(registry);
    register_card_127(registry);
    register_card_128(registry);
    register_card_129(registry);
    register_card_130(registry);
    register_card_131(registry);
    register_card_132(registry);
    register_card_133(registry);
    register_card_134(registry);
    register_card_135(registry);
    register_card_136(registry);
    register_card_137(registry);
    register_card_138(registry);
    register_card_139(registry);
    register_card_140(registry);
    register_card_141(registry);
    register_card_142(registry);
    register_card_143(registry);
    register_card_144(registry);
    register_card_145(registry);
    register_card_146(registry);
    register_card_147(registry);
    register_card_148(registry);
    register_card_149(registry);
    register_card_150(registry);
    register_card_151(registry);
    register_card_152(registry);
    register_card_153(registry);
    register_card_154(registry);
    register_card_155(registry);
    register_card_156(registry);
    register_card_157(registry);
    register_card_158(registry);
    register_card_159(registry);
    register_card_160(registry);
    register_card_161(registry);
    register_card_162(registry);
    register_card_163(registry);
    register_card_164(registry);
    register_card_165(registry);
    register_card_166(registry);
    register_card_167(registry);
    register_card_168(registry);
    register_card_169(registry);
    register_card_170(registry);
    register_card_171(registry);
    register_card_172(registry);
    register_card_173(registry);
    register_card_174(registry);
    register_card_175(registry);
    register_card_176(registry);
    register_card_177(registry);
    register_card_178(registry);
    register_card_179(registry);
    register_card_180(registry);
    register_card_181(registry);
    register_card_182(registry);
    register_card_183(registry);
    register_card_184(registry);
    register_card_185(registry);
    register_card_186(registry);
    register_card_187(registry);
    register_card_188(registry);
    register_card_189(registry);
    register_card_190(registry);
    register_card_191(registry);
    register_card_192(registry);
    register_card_193(registry);
    register_card_194(registry);
    register_card_195(registry);
    register_card_196(registry);
    register_card_197(registry);
    register_card_198(registry);
    register_card_199(registry);
    register_card_200(registry);
    register_card_201(registry);
    register_card_202(registry);
    register_card_203(registry);
    register_card_204(registry);
    register_card_205(registry);
    register_card_206(registry);
    register_card_207(registry);
    register_card_208(registry);
    register_card_209(registry);
    register_card_210(registry);
    register_card_211(registry);
    register_card_212(registry);
    register_card_213(registry);
    register_card_214(registry);
    register_card_215(registry);
    register_card_216(registry);
    register_card_217(registry);
    register_card_218(registry);
    register_card_219(registry);
    register_card_220(registry);
    register_card_221(registry);
    register_card_222(registry);
    register_card_223(registry);
    register_card_224(registry);
    register_card_225(registry);
    register_card_226(registry);
    register_card_227(registry);
    register_card_228(registry);
    register_card_229(registry);
    register_card_230(registry);
    register_card_231(registry);
    register_card_232(registry);
    register_card_233(registry);
    register_card_234(registry);
    register_card_235(registry);
    register_card_236(registry);
    register_card_237(registry);
    register_card_238(registry);
    register_card_239(registry);
    register_card_240(registry);
    register_card_241(registry);
    register_card_242(registry);
    register_card_243(registry);
    register_card_244(registry);
    register_card_245(registry);
    register_card_246(registry);
    register_card_247(registry);
    register_card_248(registry);
    register_card_249(registry);
    register_card_250(registry);
    register_card_251(registry);
    register_card_252(registry);
    register_card_253(registry);
    register_card_254(registry);
    register_card_255(registry);
    register_card_256(registry);
    register_card_257(registry);
    register_card_258(registry);
    register_card_259(registry);
    register_card_260(registry);
    register_card_261(registry);
    register_card_262(registry);
    register_card_263(registry);
    register_card_264(registry);
    register_card_265(registry);
    register_card_266(registry);
    register_card_267(registry);
    register_card_268(registry);
    register_card_269(registry);
    register_card_270(registry);
    register_card_271(registry);
    register_card_272(registry);
    register_card_273(registry);
    register_card_274(registry);
    register_card_275(registry);
    register_card_276(registry);
    register_card_277(registry);
    register_card_278(registry);
    register_card_279(registry);
    register_card_280(registry);
    register_card_281(registry);
    register_card_282(registry);
    register_card_283(registry);
    register_card_284(registry);
    register_card_285(registry);
    register_card_286(registry);
    register_card_287(registry);
    register_card_288(registry);
    register_card_289(registry);
    register_card_290(registry);
    register_card_291(registry);
    register_card_292(registry);
    register_card_293(registry);
    register_card_294(registry);
    register_card_295(registry);
    register_card_296(registry);
    register_card_297(registry);
    register_card_298(registry);
    register_card_299(registry);
    register_card_300(registry);
    register_card_301(registry);
    register_card_302(registry);
    register_card_303(registry);
    register_card_304(registry);
    register_card_305(registry);
    register_card_306(registry);
    register_card_307(registry);
    register_card_308(registry);
    register_card_309(registry);
    register_card_310(registry);
    register_card_311(registry);
    register_card_312(registry);
    register_card_313(registry);
    register_card_314(registry);
    register_card_315(registry);
    register_card_316(registry);
    register_card_317(registry);
    register_card_318(registry);
    register_card_319(registry);
    register_card_320(registry);
    register_card_321(registry);
    register_card_322(registry);
    register_card_323(registry);
    register_card_324(registry);
    register_card_325(registry);
    register_card_326(registry);
    register_card_327(registry);
    register_card_328(registry);
    register_card_329(registry);
    register_card_330(registry);
    register_card_331(registry);
    register_card_332(registry);
    register_card_333(registry);
    register_card_334(registry);
    register_card_335(registry);
    register_card_336(registry);
    register_card_337(registry);
    register_card_338(registry);
    register_card_339(registry);
    register_card_340(registry);
    register_card_341(registry);
    register_card_342(registry);
    register_card_343(registry);
    register_card_344(registry);
    register_card_345(registry);
    register_card_346(registry);
    register_card_347(registry);
    register_card_348(registry);
    register_card_349(registry);
    register_card_350(registry);
    register_card_351(registry);
    register_card_352(registry);
    register_card_353(registry);
    register_card_354(registry);
    register_card_355(registry);
    register_card_356(registry);
    register_card_357(registry);
    register_card_358(registry);
    register_card_359(registry);
    register_card_360(registry);
    register_card_361(registry);
    register_card_362(registry);
    register_card_363(registry);
    register_card_364(registry);
    register_card_365(registry);
    register_card_366(registry);
    register_card_367(registry);
    register_card_368(registry);
    register_card_369(registry);
    register_card_370(registry);
    register_card_371(registry);
    register_card_372(registry);
    register_card_373(registry);
    register_card_374(registry);
    register_card_375(registry);
    register_card_376(registry);
    register_card_377(registry);
    register_card_378(registry);
    register_card_379(registry);
    register_card_380(registry);
    register_card_381(registry);
    register_card_382(registry);
    register_card_383(registry);
    register_card_384(registry);
    register_card_385(registry);
    register_card_386(registry);
    register_card_387(registry);
    register_card_388(registry);
    register_card_389(registry);
    register_card_390(registry);
    register_card_391(registry);
    register_card_392(registry);
    register_card_393(registry);
    register_card_394(registry);
    register_card_395(registry);
    register_card_396(registry);
    register_card_397(registry);
    register_card_398(registry);
    register_card_399(registry);
    register_card_400(registry);
    register_card_401(registry);
    register_card_402(registry);
    register_card_403(registry);
    register_card_404(registry);
    register_card_405(registry);
    register_card_406(registry);
    register_card_407(registry);
    register_card_408(registry);
    register_card_409(registry);
    register_card_410(registry);
    register_card_411(registry);
    register_card_412(registry);
    register_card_413(registry);
    register_card_414(registry);
    register_card_415(registry);
    register_card_416(registry);
    register_card_417(registry);
    register_card_418(registry);
    register_card_419(registry);
    register_card_420(registry);
    register_card_421(registry);
    register_card_422(registry);
    register_card_423(registry);
    register_card_424(registry);
    register_card_425(registry);
    register_card_426(registry);
    register_card_427(registry);
    register_card_428(registry);
    register_card_429(registry);
    register_card_430(registry);
    register_card_431(registry);
    register_card_432(registry);
    register_card_433(registry);
    register_card_434(registry);
    register_card_435(registry);
    register_card_436(registry);
    register_card_437(registry);
    register_card_438(registry);
    register_card_439(registry);
    register_card_440(registry);
    register_card_441(registry);
    register_card_442(registry);
    register_card_443(registry);
    register_card_444(registry);
    register_card_445(registry);
    register_card_446(registry);
    register_card_447(registry);
    register_card_448(registry);
    register_card_449(registry);
    register_card_450(registry);
    register_card_451(registry);
    register_card_452(registry);
    register_card_453(registry);
    register_card_454(registry);
    register_card_455(registry);
    register_card_456(registry);
    register_card_457(registry);
    register_card_458(registry);
    register_card_459(registry);
    register_card_460(registry);
    register_card_461(registry);
    register_card_462(registry);
    register_card_463(registry);
    register_card_464(registry);
    register_card_465(registry);
    register_card_466(registry);
    register_card_467(registry);
    register_card_468(registry);
    register_card_469(registry);
    register_card_470(registry);
    register_card_471(registry);
    register_card_472(registry);
    register_card_473(registry);
    register_card_474(registry);
    register_card_475(registry);
    register_card_476(registry);
    register_card_477(registry);
    register_card_478(registry);
    register_card_479(registry);
    register_card_480(registry);
    register_card_481(registry);
    register_card_482(registry);
    register_card_483(registry);
    register_card_484(registry);
    register_card_485(registry);
    register_card_486(registry);
    register_card_487(registry);
    register_card_488(registry);
    register_card_489(registry);
    register_card_490(registry);
    register_card_491(registry);
    register_card_492(registry);
    register_card_493(registry);
    register_card_494(registry);
    register_card_495(registry);
    register_card_496(registry);
    register_card_497(registry);
    register_card_498(registry);
    register_card_499(registry);
    register_card_500(registry);
    register_card_501(registry);
    register_card_502(registry);
    register_card_503(registry);
    register_card_504(registry);
    register_card_505(registry);
    register_card_506(registry);
    register_card_507(registry);
    register_card_508(registry);
    register_card_509(registry);
    register_card_510(registry);
    register_card_511(registry);
    register_card_512(registry);
    register_card_513(registry);
    register_card_514(registry);
    register_card_515(registry);
    register_card_516(registry);
    register_card_517(registry);
    register_card_518(registry);
    register_card_519(registry);
    register_card_520(registry);
    register_card_521(registry);
    register_card_522(registry);
    register_card_523(registry);
    register_card_524(registry);
    register_card_525(registry);
    register_card_526(registry);
    register_card_527(registry);
    register_card_528(registry);
    register_card_529(registry);
    register_card_530(registry);
    register_card_531(registry);
    register_card_532(registry);
    register_card_533(registry);
    register_card_534(registry);
    register_card_535(registry);
    register_card_536(registry);
    register_card_537(registry);
    register_card_538(registry);
    register_card_539(registry);
    register_card_540(registry);
    register_card_541(registry);
    register_card_542(registry);
    register_card_543(registry);
    register_card_544(registry);
    register_card_545(registry);
    register_card_546(registry);
    register_card_547(registry);
    register_card_548(registry);
    register_card_549(registry);
    register_card_550(registry);
    register_card_551(registry);
    register_card_552(registry);
    register_card_553(registry);
    register_card_554(registry);
    register_card_555(registry);
    register_card_556(registry);
    register_card_557(registry);
    register_card_558(registry);
    register_card_559(registry);
    register_card_560(registry);
    register_card_561(registry);
    register_card_562(registry);
    register_card_563(registry);
    register_card_564(registry);
    register_card_565(registry);
    register_card_566(registry);
    register_card_567(registry);
    register_card_568(registry);
    register_card_569(registry);
    register_card_570(registry);
    register_card_571(registry);
    register_card_572(registry);
    register_card_573(registry);
    register_card_574(registry);
    register_card_575(registry);
    register_card_576(registry);
    register_card_577(registry);
    register_card_578(registry);
    register_card_579(registry);
    register_card_580(registry);
    register_card_581(registry);
    register_card_582(registry);
    register_card_583(registry);
    register_card_584(registry);
    register_card_585(registry);
    register_card_586(registry);
    register_card_587(registry);
    register_card_588(registry);
    register_card_589(registry);
    register_card_590(registry);
    register_card_591(registry);
    register_card_592(registry);
    register_card_593(registry);
    register_card_594(registry);
    register_card_595(registry);
    register_card_596(registry);
    register_card_597(registry);
    register_card_598(registry);
    register_card_599(registry);
    register_card_600(registry);
    register_card_601(registry);
    register_card_602(registry);
    register_card_603(registry);
    register_card_604(registry);
    register_card_605(registry);
    register_card_606(registry);
    register_card_607(registry);
    register_card_608(registry);
    register_card_609(registry);
    register_card_610(registry);
    register_card_611(registry);
    register_card_612(registry);
    register_card_613(registry);
    register_card_614(registry);
    register_card_615(registry);
    register_card_616(registry);
    register_card_617(registry);
    register_card_618(registry);
    register_card_619(registry);
    register_card_620(registry);
    register_card_621(registry);
    register_card_622(registry);
    register_card_623(registry);
    register_card_624(registry);
    register_card_625(registry);
    register_card_626(registry);
    register_card_627(registry);
    register_card_628(registry);
    register_card_629(registry);
    register_card_630(registry);
    register_card_631(registry);
    register_card_632(registry);
    register_card_633(registry);
    register_card_634(registry);
    register_card_635(registry);
    register_card_636(registry);
    register_card_637(registry);
    register_card_638(registry);
    register_card_639(registry);
    register_card_640(registry);
    register_card_641(registry);
    register_card_642(registry);
    register_card_643(registry);
    register_card_644(registry);
    register_card_645(registry);
    register_card_646(registry);
    register_card_647(registry);
    register_card_648(registry);
    register_card_649(registry);
    register_card_650(registry);
    register_card_651(registry);
    register_card_652(registry);
    register_card_653(registry);
    register_card_654(registry);
    register_card_655(registry);
    register_card_656(registry);
    register_card_657(registry);
    register_card_658(registry);
    register_card_659(registry);
    register_card_660(registry);
    register_card_661(registry);
    register_card_662(registry);
    register_card_663(registry);
    register_card_664(registry);
    register_card_665(registry);
    register_card_666(registry);
    register_card_667(registry);
    register_card_668(registry);
    register_card_669(registry);
    register_card_670(registry);
    register_card_671(registry);
    register_card_672(registry);
    register_card_673(registry);
    register_card_674(registry);
    register_card_675(registry);
    register_card_676(registry);
    register_card_677(registry);
    register_card_678(registry);
    register_card_679(registry);
    register_card_680(registry);
    register_card_681(registry);
    register_card_682(registry);
    register_card_683(registry);
    register_card_684(registry);
    register_card_685(registry);
    register_card_686(registry);
    register_card_687(registry);
    register_card_688(registry);
    register_card_689(registry);
    register_card_690(registry);
    register_card_691(registry);
    register_card_692(registry);
    register_card_693(registry);
    register_card_694(registry);
    register_card_695(registry);
    register_card_696(registry);
    register_card_697(registry);
    register_card_698(registry);
    register_card_699(registry);
    register_card_700(registry);
    register_card_701(registry);
    register_card_702(registry);
    register_card_703(registry);
    register_card_704(registry);
    register_card_705(registry);
    register_card_706(registry);
    register_card_707(registry);
    register_card_708(registry);
    register_card_709(registry);
    register_card_710(registry);
    register_card_711(registry);
    register_card_712(registry);
    register_card_713(registry);
    register_card_714(registry);
    register_card_715(registry);
    register_card_716(registry);
    register_card_717(registry);
    register_card_718(registry);
    register_card_719(registry);
    register_card_720(registry);
    register_card_721(registry);
    register_card_722(registry);
    register_card_723(registry);
    register_card_724(registry);
    register_card_725(registry);
    register_card_726(registry);
    register_card_727(registry);
    register_card_728(registry);
    register_card_729(registry);
    register_card_730(registry);
    register_card_731(registry);
    register_card_732(registry);
    register_card_733(registry);
    register_card_734(registry);
    register_card_735(registry);
    register_card_736(registry);
    register_card_737(registry);
    register_card_738(registry);
    register_card_739(registry);
    register_card_740(registry);
    register_card_741(registry);
    register_card_742(registry);
    register_card_743(registry);
    register_card_744(registry);
    register_card_745(registry);
    register_card_746(registry);
    register_card_747(registry);
    register_card_748(registry);
    register_card_749(registry);
    register_card_750(registry);
    register_card_751(registry);
    register_card_752(registry);
    register_card_753(registry);
    register_card_754(registry);
    register_card_755(registry);
    register_card_756(registry);
    register_card_757(registry);
    register_card_758(registry);
    register_card_759(registry);
    register_card_760(registry);
    register_card_761(registry);
    register_card_762(registry);
    register_card_763(registry);
    register_card_764(registry);
    register_card_765(registry);
    register_card_766(registry);
    register_card_767(registry);
    register_card_768(registry);
    register_card_769(registry);
    register_card_770(registry);
    register_card_771(registry);
    register_card_772(registry);
    register_card_773(registry);
    register_card_774(registry);
    register_card_775(registry);
    register_card_776(registry);
    register_card_777(registry);
    register_card_778(registry);
    register_card_779(registry);
    register_card_780(registry);
    register_card_781(registry);
    register_card_782(registry);
    register_card_783(registry);
    register_card_784(registry);
    register_card_785(registry);
    register_card_786(registry);
    register_card_787(registry);
}

} // namespace riftbound
